### PR TITLE
Azure pipelines

### PR DESCRIPTION
**Pull request by steaward**
This PR adds continuous integration with Azure Pipelines. 

It just simply runs two scripts before the PR -> npm install and npm build. 
Right now I don't know what exactly we want the preferred build to be, so it just returns true. The script commands can be found in the `package.json` file. 

In the near future, we should have it automatically deploy to Azure Marketplace, where VSCode extensions can be found(this is the reason why I chose Azure Pipelines).

### CODE REVIEW

**Comment by Michael-Overall** [comment]
Since there is currently no script defined for npm build, this script in its current implementation only checks if npm install succeeds. 

In terms of getting others to test this, how should we do this? I don't think I can fork your fork of CodeTalker to make a PR to your azure-pipelines branch (and try to push a PR that is intended to fail the npm i command, and one that passes). 

Do the tests actually automatically occur when you make a PR by virtue of including those scripts, or as a repo owner, did you need to allow access to some kind of app via OAUTH, etc?

**Comment by steaward** [comment]
Sorry for the late response...

Yes, Azure Pipelines fires all off scripts before the build is complete. Any errors, and the PR will be flagged. 

We don't have a build script, other than npm build. By default, this happens already, that is why I have it returning 'true'. When I was setting azure pipelines up , it complained over again that there was no build process. I came to the conclusion that we had to add a 'build' script in the meantime. 

In terms of testing, any test that are under the test directory are run. I honestly think this system resembles TravisCI quite a bit.

**Review by PopeSpaceous — COMMENTED** [review]
@steaward, is this setup on a unix system only?
If not how can we test this on other systems?

**Review by PopeSpaceous — APPROVED** [review]
Looks good! 
Thanks @steaward

**Pull request merged**
